### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by manhg** [FSX/momoko#104]
Hi,
Thanks for your great works.
I had problem using Momoko using Future as in latest document. 
Finally I found the problem: the release in PyPI is Momoko 1.x!
Please release Momoko 2.x; so by default, generator based usage is available.

**Comment by haizaar** [comment]
Great you liked it. Pushed 2.0.0 to PyPi just now. Enjoy!

**Comment by manhg** [comment]
Thank you!

**Comment by haizaar** [comment]
Feel free to post more bugs! :)
