### ISSUE TITLE
env var set fails with pip install

### ISSUE THREAD

**Issue by lsmag** [FSX/momoko#113]
Hi,

I was trying to install Momoko with psycopg2cffi, your setup instructions work fine when I download the package and install it directly (`MOMOKO_PSYCOPG2_IMPL=psycopg2cffi python setup.py install`), but it fails when I try it with pip:

    MOMOKO_PSYCOPG2_IMPL=psycopg2cffi pip install momoko

It'll always install psycopg2 instead. I assume this is a particular behaviour of pip (though not a bug, I believe), so it might be fine. Also, I use pip just indirectly with `pip-tools`. mostly `pip-sync` to do the first install.

So, there are two things here:
 - first, shouldn't be momoko+psycopg2cffi be installable through pip using the form I used above? It is certainly handier than `download -> unpack -> install -> cleanup`.
 - second, I use a package called [Mistune](https://github.com/lepture/mistune), which uses a [specific way](https://github.com/lepture/mistune/blob/master/setup.py#L16) to declare dependencies. What do you think, could that be done here too?

Like:

    $ pip install psycopg2cffi momoko
    # psycopg2cffi gets installed first, then momoko drops the psycopg2 dependency

As a bonus, it'll also work with `pip-tools`. I can make a PR with this new install method without dropping the current one (which tests rely on, if I'm not mistaken).

**Comment by haizaar** [comment]
I guess pip looks up dependencies on PyPi and momoko is registered on PyPi with `psycopg2` dependency. I deduce this from the fact that pip downloads all of the stuff before installing it.

Regarding your second question, I frankly did not understand how do you declare dependencies there. Can you elaborate?

**Comment by haizaar** [comment]
Well, I had a look at pip [docs](https://pip.pypa.io/en/latest/user_guide.html). They say:
>It's important to be clear that pip determines package dependencies using install_requires metadata, not by discovering requirements.txt files embedded in projects.

If it loads `setup.py` and uses [`install_requires`](http://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies), then your trick should work. I suggest you try hacking `pip` to find out what's going on.
