### ISSUE TITLE
Due to set_exc_info momoko2 does not work on Tornado 3.x

### ISSUE THREAD

**Issue by friedcell** [FSX/momoko#117]
I see two options:
- require tornado 4.x for momoko2 [affects docs only]
- check for set_exc_info (and set_exception_info from concurrent.futures>=2.2.0?) existence before use [needs code update + tests]

Noticed while selectively upgrading packages on a project, did not find a notice in docs.

**Comment by haizaar** [comment]
Well, momoko 2.x explicitly requires tornado >= 4.0.0 in setup.py. Where else do you suggest to add notes?

**Comment by friedcell** [comment]
Saw that after posting the comment. I'd say in the **Important** notice in readme - I can create a PR if needed.

**Comment by haizaar** [comment]
Sure, go on with PR please.

**Comment by haizaar** [comment]
Fixed by #119
