### ISSUE TITLE
How can I run the first sample of momoko

### ISSUE THREAD

**Issue by yoosofan** [FSX/momoko#143]
My project needs time consuming queries. Therefore, Momoko seems the best answer.But I couldn't even run the first sample of Momoko. What is the problem of the following code:

    import psycopg2
    import momoko
    from tornado.ioloop import IOLoop
    ioloop = IOLoop.instance()

    dsn= 'dbname=db1 user=postgres password=myPass host=127.0.0.1 port=5432'
    conn = momoko.Connection(dsn=dsn)
    future = ioloop.add_future(conn.connect(), lambda x: ioloop.stop())
    ioloop.start()
    print(type(future))
    future.result()  # raises exception on connection error

    future = conn.execute("SELECT 1")
    ioloop.add_future(future, lambda x: ioloop.stop())
    ioloop.start()
    cursor = future.result()
    rows = cursor.fetchall()
    for m1 in rows:
      print(m1)

Error : Python3 on Ubuntu 16.04 with latest packages
<class 'NoneType'>
Traceback (most recent call last):
  File "test.01.py", line 11, in <module>
    future.result()  # raises exception on connection error
AttributeError: 'NoneType' object has no attribute 'result'

**Comment by haizaar** [comment]
How about

```
future = conn.connect()
ioloop.add_future(future, lambda x: ioloop.stop())
ioloop.start()
...
```

**Comment by haizaar** [comment]
Btw,
You don't really need a future for `connect`  operation.

**Comment by yoosofan** [comment]
Thank you, my problem solved. The corrected code is:

    import psycopg2
    import momoko
    from tornado.ioloop import IOLoop
    ioloop = IOLoop.instance()

    dsn = "dbname=db user=postgres password=myPass host=127.0.0.1 port=5432"
    conn = momoko.Pool(dsn=dsn)
    future = conn.connect()
    ioloop.add_future(future, lambda x: ioloop.stop())
    ioloop.start()
    future.result()  # raises exception on connection error

    future = conn.execute("SELECT 1")
    ioloop.add_future(future, lambda x: ioloop.stop())
    ioloop.start()
    cursor = future.result()
    rows = cursor.fetchall()
    for m1 in rows:
      print(m1)

**Comment by yoosofan** [comment]
Please change the sample of the first page on [tutorial](http://momoko.61924.nl/en/latest/tutorial.html)

**Comment by yoosofan** [comment]
Here is simpler code:

    import psycopg2
    import momoko
    from tornado.ioloop import IOLoop
    ioloop = IOLoop.instance()

    dsn = "dbname=db user=postgres password=myPass host=127.0.0.1 port=5432"
    conn = momoko.Pool(dsn=dsn)
    ioloop.add_future(conn.connect(), lambda x: ioloop.stop())
    ioloop.start()

    future = conn.execute("SELECT 1")
    ioloop.add_future(future, lambda x: ioloop.stop())
    ioloop.start()
    cursor = future.result()
    rows = cursor.fetchall()
    for m1 in rows:      print(m1)

**Comment by haizaar** [comment]
My bad - you do need to check `future`'s result for connect operation if you want to catch connection errors.
