### ISSUE TITLE
NamedTupleCursor factory test is executed even if MOMOKO_TEST_HSTORE is disabled

### ISSUE THREAD

**Issue by rmedaer** [FSX/momoko#159]
The unit test  `test_cursor_factory_with_extensions` is testing that NamedTupleCursor factory is working with **both** hstore and json.
However, if `MOMOKO_TEST_HSTORE` is disabled we should only test _json_ !

A quick fix would be to split the unit test in:
  - `test_cursor_factory_with_json_extension` to test JSON
  - `test_cursor_factory_with_hstore_extension` to test HSTORE extension and add the following decorator `@unittest.skipIf(not test_hstore, "Skipping test as requested")`

Is it OK for you ? Would you like that I make a pull request with it ?

**Comment by haizaar** [comment]
Good point. Indeed, please go ahead with pull request if you can.
