### ISSUE TITLE
register_composite

### ISSUE THREAD

**Issue by subssn21** [FSX/momoko#99]
I wanted to register a composite using morocco, I tried several things and ended up temporarily creating a regular pscopg2 connection to register the composite globally. 

The problem is that the CompositeCaster class queries the database to get the kids, I tried to follow the pattern you have established with the register store code, but I wasn't having much luck.

**Comment by haizaar** [comment]
Sorry, not replying earlier.

It seems you are on the right way - try doing it the same way as `register_hstore`. You need to implement it both for Connection and Pool classes.

If you can paste some code that you are having trouble with, I can help.

**Comment by haizaar** [comment]
Closing as inactive.
